wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: FFNN (4*32)
activation function:
  desc: null
  value: Tanh
Weight decay:
  desc: null
  value: 1.0e-06
epochs:
  desc: null
  value: 5000
ODE loss:
  desc: null
  value: 'yes'
IC loss:
  desc: null
  value: 'yes'
Data points:
  desc: null
  value: 'true'
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1701383766.867303
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.16.0
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
